version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 031485421365.dkr.ecr.ap-southeast-2.amazonaws.com/youtube
  build:
    commands:
      - docker build -t youtube:latest .
      - docker tag youtube:latest 031485421365.dkr.ecr.ap-southeast-2.amazonaws.com/youtube:latest
  post_build:
    commands:
      - docker push 031485421365.dkr.ecr.ap-southeast-2.amazonaws.com/youtube:latest
      - printf '[{"name":"helloWorld","imageUri":"%s"}]' 
      031485421365.dkr.ecr.ap-southeast-2.amazonaws.com/youtube:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
