version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin public.ecr.aws/p8c5p9n0/youtube
    commands:
      - docker build -t youtube:latest .
      - docker tag youtube:latest public.ecr.aws/p8c5p9n0/youtube:latest
  post_build:
    commands:
      - docker push public.ecr.aws/p8c5p9n0/youtube:latest
      - printf '[{"name":"helloWorld","imageUri":"%s"}]' 
      public.ecr.aws/p8c5p9n0/youtube:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
